server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id : DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/department-service-fallback

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name : USER-SERVICE
                fallbackuri : forward:/user-service-fallback

management:
  endpoints:
    web:
      exposure:
        include : hystrix.stream

hystrix :
  command :
    fallbackcmd :
      execution :
        isolation :
          thread :
            timeoutInMilliseconds : 4000